import React, { useState, useEffect } from "react";
import Head from 'next/head'
import { Container, Button, Row, Col } from 'react-bootstrap'
import Sidebar from '../components/Sidebar'
import DashBoardHeader from '../components/DashBoardHeader'
import styles from '../styles/dashboard.module.scss'

const columns = [
  {
    Header: 'Target',
    accessor: 'target', // Property name in your data
  },
  {
    Header: 'Activity',
    accessor: 'activity',
  },
  {
    Header: 'Window Start',
    accessor: 'windowStart',
  },
  {
    Header: 'WindowEnd',
    accessor: 'windowEnd',
  },
  {
    Header: 'Duration',
    accessor: 'duration',
  },
  {
    Header: 'RepeatCycle Frequency MinimumGap',
    accessor: 'repeatCycleFrequencyMinimumGap',
  },
  {
    Header: 'RepeatCycle Frequency MaximumGap',
    accessor: 'repeatCycleFrequencyMaximumGap',
  },
  {
    Header: 'RepeatCycle Repetition',
    accessor: 'repeatCycleRepetition',
  },
  {
    Header: 'PayloadOutage',
    accessor: 'payloadOutage',
  },
  {
    Header: '',
    accessor: 'actions',
    Cell: () => (
      <Button type="button">Decline</Button>
    ),
  },
  // Add more columns as needed
];

const data = [{
  target: "SOSO-1",
  activity: "MemoryScrub",
  windowStart: "2023-10-08 T00:00:00",
  windowEnd: "2023-10-15 T23:59:59",
  duration: "180",
  repeatCycleFrequencyMinimumGap: "144000",
  repeatCycleFrequencyMaximumGap: "216000",
  repeatCycleRepetition: "3",
  payloadOutage: "TRUE"
}];

export default function Home() {
  // uncomment the below line when you add link in axios
  // const [data, setData] = useState([]);
  const [hideShowSidebar, setHideShowSidebar] = useState(true);
  
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='dashboard'>
        <Sidebar/>
        <DashBoardHeader />
        <div className="dashboardContent">
          <div className={styles.dashboardMainContent}>
            <Container className={styles.container}>
              <Row>
                <Col sm={12}>
                  <div className={styles.graphCardWrap}>
                    <h6>Events Rate</h6>
                    <div className={styles.graphCard}>
                      {/* add graph here */}
                    </div>
                  </div>
                </Col>
                <Col sm={12} md={4}>
                  <div className={styles.graphCardWrap}>
                    <h6>Total/Faulty Panels</h6>
                    <div className={styles.graphCard}>
                      {/* add graph here */}
                    </div>
                  </div>
                </Col>
                <Col sm={12} md={4}>
                  <div className={styles.graphCardWrap}>
                    <h6>All Processes</h6>
                    <div className={styles.graphCard}>
                      {/* add graph here */}
                    </div>
                  </div>
                </Col>
                <Col sm={12} md={4}>
                  <div className={styles.graphCardWrap}>
                    <h6>Online (Supervision) / Connected Panels</h6>
                    <div className={styles.graphCard}>
                      {/* add graph here */}
                    </div>
                  </div>
                </Col>
              </Row>
            </Container>
          </div>
        </div>
      </main>
    </>
  )
}
